<#
.SYNOPSIS
    Packs every local DevKit target project at the version stored in .vscode\zekelin-dotnet-tools.json
    and installs them into the local NuGet feed.

.DESCRIPTION
    Generated by the "Zekelin .NET Tools" VS Code extension. Mirrors its "Install targets Nugets" action.

    1. Reads packLocalVersion from <repoRoot>\.vscode\zekelin-dotnet-tools.json.
    2. Resolves the local NuGet feed:
       - reuses a source named "Local" / "local" (case-insensitive), or
       - any existing source whose path already matches C:\NuGetLocal, or
       - registers a new "Local" source at C:\NuGetLocal.
    3. Packs every *.csproj under src\Dataverse\ plus src\Sdk\TALXIS.DevKit.Build.Sdk.csproj (if present)
       with -p:PackageVersion=$version into <repoRoot>\artifacts\.
    4. Copies every *.nupkg from <repoRoot>\artifacts\ into the resolved local feed.
    5. Kills every running dotnet.exe.
    6. Clears the NuGet cache (dotnet nuget locals all --clear).

    MUST be run before testing any change made under src\Dataverse\ or src\Sdk\ — otherwise downstream
    consumers will keep resolving the previously cached or previously published NuGet version.
#>

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path $PSScriptRoot -Parent

$configDir  = Join-Path $RepoRoot ".vscode"
$configPath = Join-Path $configDir "zekelin-dotnet-tools.json"

if (-not (Test-Path $configPath)) {
    Write-Host "Version config not found: $configPath" -ForegroundColor Red
    Write-Host "Open the 'Zekelin .NET Tools' sidebar in VS Code and click 'Install targets Nugets' or 'Generate Install Script' once to initialise the version." -ForegroundColor Yellow
    exit 1
}

try {
    $cfg = Get-Content $configPath -Raw | ConvertFrom-Json
    $version = [string]$cfg.packLocalVersion
} catch {
    Write-Host "Failed to parse ${configPath}: $_" -ForegroundColor Red
    exit 1
}

if ([string]::IsNullOrWhiteSpace($version)) {
    Write-Host "packLocalVersion is empty in $configPath" -ForegroundColor Red
    exit 1
}

Write-Host "Using version: $version" -ForegroundColor Cyan

Write-Host "`n=== Resolving Local NuGet source ===" -ForegroundColor Cyan
$sourcesRaw = dotnet nuget list source | Out-String
$lines = $sourcesRaw -split "`r?`n"

$parsed = @()
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match '^\s*\d+\.\s+(\S+)\s+\[(?:Enabled|Disabled)\]') {
        $name = $Matches[1]
        $j = $i + 1
        while ($j -lt $lines.Count -and [string]::IsNullOrWhiteSpace($lines[$j])) { $j++ }
        if ($j -lt $lines.Count) {
            $parsed += [pscustomobject]@{ Name = $name; Url = $lines[$j].Trim() }
        }
    }
}

$defaultFeed = "C:\NuGetLocal"
$localFeed = $null

$byName = $parsed | Where-Object { $_.Name.ToLower() -eq "local" } | Select-Object -First 1
if ($byName) {
    $localFeed = $byName.Url
    Write-Host "Found existing source '$($byName.Name)': $localFeed" -ForegroundColor Green
}

if (-not $localFeed) {
    $byPath = $parsed | Where-Object { $_.Url.TrimEnd('\','/').ToLower() -eq $defaultFeed.ToLower() } | Select-Object -First 1
    if ($byPath) {
        $localFeed = $byPath.Url
        Write-Host "Found existing source at $localFeed (registered as '$($byPath.Name)') - reusing" -ForegroundColor Green
    }
}

if (-not $localFeed) {
    Write-Host "No 'Local' NuGet source found - registering $defaultFeed as 'Local' ..."
    if (-not (Test-Path $defaultFeed)) { New-Item -ItemType Directory -Path $defaultFeed -Force | Out-Null }
    dotnet nuget add source $defaultFeed --name Local
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to register NuGet source" -ForegroundColor Red
        exit 1
    }
    $localFeed = $defaultFeed
}

if (-not (Test-Path $localFeed)) { New-Item -ItemType Directory -Path $localFeed -Force | Out-Null }

$dataverseSrc = Join-Path $RepoRoot "src\Dataverse"
$sdkProj      = Join-Path $RepoRoot "src\Sdk\TALXIS.DevKit.Build.Sdk.csproj"

$projects = @()
if (Test-Path $dataverseSrc) { $projects += Get-ChildItem -Path $dataverseSrc -Filter "*.csproj" -Recurse }
if (Test-Path $sdkProj)      { $projects += Get-Item $sdkProj }

if ($projects.Count -eq 0) {
    Write-Host "No .csproj files found under src\Dataverse or src\Sdk" -ForegroundColor Red
    exit 1
}

$artifacts = Join-Path $RepoRoot "artifacts"
if (-not (Test-Path $artifacts)) { New-Item -ItemType Directory -Path $artifacts -Force | Out-Null }

Write-Host "`n=== Packing $($projects.Count) project(s) with version $version ===" -ForegroundColor Cyan
$idx = 0
foreach ($proj in $projects) {
    $idx++
    Write-Host "`n($idx/$($projects.Count)) Packing $($proj.Name) ..." -ForegroundColor Yellow
    dotnet pack $proj.FullName --configuration Release -p:PackageVersion=$version -p:Version=$version --output $artifacts
    if ($LASTEXITCODE -ne 0) {
        Write-Host "FAILED: $($proj.Name)" -ForegroundColor Red
        exit 1
    }
}

Write-Host "`n=== Copying .nupkg files to $localFeed ===" -ForegroundColor Cyan
Get-ChildItem -Path $artifacts -Filter "*.nupkg" | ForEach-Object {
    Copy-Item $_.FullName -Destination $localFeed -Force
    Write-Host "  Copied $($_.Name)" -ForegroundColor Green
}

Write-Host "`n=== Killing dotnet processes ===" -ForegroundColor Cyan
Get-Process -Name "dotnet" -ErrorAction SilentlyContinue | Stop-Process -Force
Write-Host "  Done" -ForegroundColor Green

Write-Host "`n=== Clearing NuGet cache ===" -ForegroundColor Cyan
dotnet nuget locals all --clear

Write-Host "`nAll done!" -ForegroundColor Green
